platform :ios, '8.0'
use_frameworks!

target "DKPhotoGalleryDemo" do
	pod 'DKPhotoGallery', :path => '../'

    target 'DKPhotoGalleryDemoUITests' do
        inherit! :search_paths
        # Pods for testing
    end

end
